name: Create RHEL7 compatible conda environment with docker

on:
  workflow_dispatch:
jobs:
  build:
    env:
      ENVIRONMENT_NAME: python3_rhel7_env
      ENVIRONMENT_FILE_PATH: python3_rhel7_env.yml
      TEST_FILE: test.sh
    runs-on: ubuntu-latest
    name: Build environment
    steps:
      - name: Free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
      - name: Build environment
        uses: slaclab/lcls-rhel7-conda-pack@v1.1
