name: Publish RHEL7 compatible nightly release

on:
  workflow_dispatch:
jobs:
  build:
    env:
      ENVIRONMENT_NAME: rhel7_devel
      ENVIRONMENT_FILE_PATH: rhel7_devel.yml
      TEST_FILE: test.sh
    runs-on: ubuntu-latest
    name: Build environment
    steps:
      - name: Free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h      
      - name: Build environment
        uses: slaclab/lcls-rhel7-conda-pack@v1.1
